export const enum Permissions {
  CREATE_STORE = 'CREATE_STORE',
  VIEW_STORE = 'VIEW_STORE',
  UPDATE_STORE = 'UPDATE_STORE',
  DELETE_STORE = 'DELETE_STORE',

  CREATE_CATEGORY = 'CREATE_CATEGORY',
  VIEW_CATEGORY = 'VIEW_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',

  CREATE_PRODUCTS = 'CREATE_PRODUCTS',
  VIEW_PRODUCTS = 'VIEW_PRODUCTS',
  UPDATE_PRODUCTS = 'UPDATE_PRODUCTS',
  DELETE_PRODUCTS = 'DELETE_PRODUCTS',
}
